### ISSUE TITLE
Searchkit not working after X-pack installation

### ISSUE THREAD

**Issue by kanishk-mehta** [searchkit/searchkit#607]
Hi,

I’ve followed all the instructions here (http://docs.searchkit.co/v0.2.0/docs/setup/elasticsearch.html) and everything was working fine till I installed X-pack,

Now searchkit is not being able to fetch data from elasticsearch. I tried adding the basic auth id and password using (basicAuth:"read:teetndhjnrspbzxxyfxmf5fb24suqxuj") as well using the (httpHeaders) in the SearchkitManager class.

I always end up getting a “Request header field Authorization is not allowed by Access-Control- Allow-Headers” error.

My CORS settings are as follows:
(http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization)

I’m new to Searchkit so please let me know if i’ve missed mentioning any further details

Please help @a-magdy @joemcelroy .

Thank you.

**Comment by a-magdy** [comment]
Hi @kanishk-mehta 

I am guessing it might be a CORS issue, can you update you elasticsearch.yml config to include:

```yaml
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-origin: "/.*/"
http.cors.allow-headers: "X-Requested-With, WWW-Authenticate, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Origin"
http.cors.allow-methods: "GET, POST, PATCH, PUT, DELETE, OPTIONS"
```

This allows more headers to __ALL__ origins, if it works for you, you need to update it to your production domain before deploying it, so that no other domains could access it -unless you want that-
